#!/usr/bin/env bash
# Generate a wal-synced bpytop theme.
set -euo pipefail

colors_json="${1:-$HOME/.cache/wal/colors.json}"
theme_out="$HOME/.config/bpytop/themes/wal.theme"

python3 - "$colors_json" "$theme_out" <<'PY'
import json
import sys
from pathlib import Path

colors_path = Path(sys.argv[1])
theme_out = Path(sys.argv[2])

# Fallback palette taken from current wal cache so first-run still looks cohesive.
fallback = {
    "foreground": "#a3b1f9",
    "background": "#050c2f",
    "cursor": "#a3b1f9",
    "color0": "#050c2f",
    "color1": "#3a34dc",
    "color2": "#582dca",
    "color3": "#7424bc",
    "color4": "#8421b0",
    "color5": "#9b1ba2",
    "color6": "#c80e88",
    "color7": "#a3b1f9",
    "color8": "#4763f3",
    "color9": "#3a34dc",
    "color10": "#582dca",
    "color11": "#7424bc",
    "color12": "#8421b0",
    "color13": "#9b1ba2",
    "color14": "#c80e88",
    "color15": "#a3b1f9",
}

data = {}
if colors_path.exists():
    try:
        data = json.loads(colors_path.read_text())
    except Exception:
        data = {}

def special(key, default_key):
    return data.get("special", {}).get(key) or fallback[default_key]

def color(name):
    return data.get("colors", {}).get(name) or data.get(name) or fallback[name]

bg = special("background", "background")
fg = special("foreground", "foreground")

accent1 = color("color8")
accent2 = color("color4")
accent3 = color("color6")
accent4 = color("color2")
dim = color("color1")

theme_lines = f"""# Generated by wal hook; do not edit manually.
theme[main_bg]="{bg}"
theme[main_fg]="{fg}"
theme[title]="{fg}"
theme[hi_fg]="{accent1}"
theme[selected_bg]="{accent2}"
theme[selected_fg]="{fg}"
theme[inactive_fg]="{dim}"
theme[graph_text]="{fg}"
theme[meter_bg]="{dim}"
theme[proc_misc]="{accent1}"
theme[cpu_box]="{accent1}"
theme[mem_box]="{accent2}"
theme[net_box]="{accent3}"
theme[proc_box]="{accent4}"
theme[div_line]="{dim}"
theme[temp_start]="{accent4}"
theme[temp_mid]="{accent2}"
theme[temp_end]="{accent3}"
theme[cpu_start]="{accent1}"
theme[cpu_mid]="{accent2}"
theme[cpu_end]="{accent3}"
theme[free_start]="{accent1}"
theme[free_mid]="{accent4}"
theme[free_end]="{accent2}"
theme[cached_start]="{fg}"
theme[cached_mid]="{accent1}"
theme[cached_end]="{accent2}"
theme[available_start]="{accent1}"
theme[available_mid]="{accent2}"
theme[available_end]="{accent4}"
theme[used_start]="{accent2}"
theme[used_mid]="{accent3}"
theme[used_end]="{accent3}"
theme[download_start]="{accent1}"
theme[download_mid]="{accent2}"
theme[download_end]="{accent3}"
theme[upload_start]="{accent4}"
theme[upload_mid]="{accent2}"
theme[upload_end]="{accent3}"
theme[process_start]="{fg}"
theme[process_mid]="{accent2}"
theme[process_end]="{dim}"
"""

theme_out.parent.mkdir(parents=True, exist_ok=True)
theme_out.write_text(theme_lines)
PY
