foreground   #a3b1f9
background   #050c2f
cursor       #a3b1f9

color0       #050c2f
color8       #4763f3
color1       #3a34dc
color9       #3a34dc
color2       #582dca
color10      #582dca
color3       #7424bc
color11      #7424bc
color4       #8421b0
color12      #8421b0
color5       #9b1ba2
color13      #9b1ba2
color6       #c80e88
color14      #c80e88
color7       #a3b1f9
color15      #a3b1f9
